version: '3.7'
services:
    dbmongo:
        container_name: dbmongo 
        build: 'backend/db'
        restart: always
        volumes:
            - ./backend/db/init:/docker-entrypoint-initdb.d
            - ./shared:/workdir/shared
            - ./backend/db/init:/workdir/init
            - ./backend/modeling/src:/workdir/src

        env_file:
            - .env
            - ./backend/db/.env
    
    modeling:
        container_name: modeling 
        build: 'backend/modeling/'
        volumes:
            - ./backend/modeling/bin:/workdir/bin
            - ./backend/modeling/src:/workdir/src
            - ./shared:/workdir/shared
            - ./mlflow/db:/workdir/data
            - ./mlflow/artifacts:/workdir/artifacts
        ports:
            - 8888:8888

        command: "jupyter notebook --allow-root --ip 0.0.0.0"
        env_file:
            - .env
            - ./backend/modeling/.env

    #independent service
    adminer:
        image: dockette/adminer:mongo
        restart: always
        ports:
            - 80:80

    mlflow:
        container_name: mlflow
        build: 'mlflow/'
        volumes:
            - ./mlflow/db:/workdir/data
            - ./mlflow/artifacts:/workdir/artifacts
        ports:
            - 5000:5000
        command : "mlflow ui --host 0.0.0.0 --backend-store-uri sqlite:///data/mlflow.db --default-artifact-root /artifacts"