version: '3.7'
services:
    web_app:
        container_name: web_app
        build: web_app/
        volumes:
            - ./web_app/:/workdir/
            - ./backend/modeling/src:/workdir/src
            - ./shared:/workdir/shared
            - ./mlflow/db:/workdir/data
            - ./mlflow/artifacts:/workdir/artifacts
        ports:
            - 8501:8501
        command: "streamlit run server.py"
        env_file:
            - .env
            - ./web_app/.env
        
    dbmongo:
        container_name: dbmongo 
        build: 'backend/db'
        restart: always
        volumes:
            - ./backend/db/init:/docker-entrypoint-initdb.d
            - ./shared:/workdir/shared
            - ./backend/modeling/src:/workdir/src

        env_file:
            - .env
            - ./backend/db/.env
    
    modeling:
        container_name: modeling 
        build: 'backend/modeling/'
        volumes:
            - ./backend/modeling/bin:/workdir/bin
            - ./backend/modeling/src:/workdir/src
            - ./shared:/workdir/shared
            - ./mlflow/db:/workdir/data
            - ./mlflow/artifacts:/workdir/artifacts
        ports:
            - 8888:8888

        command: "jupyter notebook --allow-root --ip 0.0.0.0"
        env_file:
            - .env
            - ./backend/modeling/.env

    mlflow:
        container_name: mlflow
        build: 'mlflow/'
        volumes:
            - ./mlflow/db:/workdir/data
            - ./mlflow/artifacts:/workdir/artifacts
        ports:
            - 5000:5000
        command : "mlflow ui --host 0.0.0.0 --backend-store-uri sqlite:///data/mlflow.db --default-artifact-root /workdir/artifacts"

